baseURL = "https://nitinayyagari.com/"
languageCode = "en-us"
title = "Nitin Ayyagari"
theme = "gokarna"
# disqusShortname = "username" # delete this to disable disqus comments
publishDir = "public"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Nitin Ayyagari"
    description = "Curios Engineer 路 Writer 路 Sports Buff "
    info = "Curious Engineer路 Writer 路 Sports Buff"
    githubUsername = "nrayyagari"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpeg"
    pygmentsStyle = "monokai"

    #favicon_32 = "/img/favicon-32x32.png"
    #favicon_16 = "/img/favicon-16x16.png"
    colorscheme = "light"


    hidecredits = true
    hidecopyright = false

    rtl = true

    math = true

    ShowBackToTopButton = true
    #showPostsOnHomePage = "popular"
    footer = "Nitin Ayyagari"
    
    socialIcons = [
      {name = "linkedin", url = "https://in.linkedin.com/in/nitinayyagari"},
      {name = "email", url = "nitinayyagari@outlook.com"},
    ]

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4

[[menu.main]]
    url = "/pdf/linux.pdf"
    name = "Resume"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
